# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/iharuki79"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name = "X(Twitter)"
    url = "https://x.com/Hals_AC"

    [social.params]
        icon = "brand-twitter"
