# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/iharuki79"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "x"
    name = "X(Twitter)"
    url = "https://x.com/one_hals"

    [social.params]
        icon = "brand-x"

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/iharuki/"

    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "facebook"
    name = "facebook"
    url = "https://www.facebook.com/haruki.ishikawa.330/"

    [social.params]
        icon = "brand-facebook"
